baseURL = 'https://colbal.com/'
languageCode = 'en-us'
title = 'Small Business Technology Consultant'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "/images/favicon/favicon.ico"
  site_logo = "/images/logo/colbal-site-logo_108x123.png"
  description = "Dynamic Technology and Business Solutions"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 1