enableRobotsTXT: true
languageCode: en-us
params:
  site_logo: /images/logo/circle_blue_logo.svg
  mainSections:
    - posts
  background_color_class: bg-navy
  author: ""
  phone: "+6038510727"
  hugo_tips_playlist:
    link: https://youtube.com/playlist?list=PLWRhfI3EDQ8DmUvR7evCoGfBpnT368IXu&si=gjuUQHRu3LX8CYED
    title: ""
  text_color: ""
  tip_article:
    link: /posts/why-not-wordpress
    title: Why not Wordpress?
  favicon: images/circle_blue_logo.svg
  recent_posts_number: 3
  email: contact-us@colbal.com
  description: "Providing technology consulting to new and existing small
    businesses through web design, software improvements, data management and
    information security. "
  address1: Chandler, AZ
  address2: New Hampshire
theme: ananke
googleAnalytics: ""
DefaultContentLanguage: en
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
title: "Colbal | Small Business Technology Consultant  "
baseURL: https://www.colbal.com/
