baseURL: 'https://colbal.com/'
languageCode: en-us
title: 'Colbal | Small Business Technology Consultant  '
theme: 'ananke' #'colbal'  

### start comment out for 'ananke' theme

# menu:
#   main:
#   - identifier: services
#     name: Services
#     pageRef: /services
#     weight: 10
#   - name: Contact us
#     pageRef: /contact
#     weight: 20
#   - name: Articles
#     pageRef: /posts
#     weight: 30
#   - name: About
#     pageRef: /about
#     weight: 40
#   - name: FAQ
#     pageRef: /fag
#     weight: 50

### end comment out

DefaultContentLanguage: "en"
# sectionPagesMenu: main
# Paginate: 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics: ""
enableRobotsTXT: true

sitemap:
  changefreq: "monthly"
  priority: 0.5 
  filename: "sitemap.xml"

params:
  text_color: ""
  author: ""
  favicon: "/images/favicon/favicon.ico"
  site_logo: "/images/logo/circle-logo_82x80.png"
  description: "Providing technology consulting to new and existing small businesses through web design, software improvements, data management and information security. "
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-navy"
  recent_posts_number: 3